# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swift-webview-integration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift-webview-integration
  pod 'Runtime'

  target 'swift-webview-integrationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swift-webview-integrationUITests' do
    # Pods for testing
  end

end
